# fly.toml file generated for voberoi-protohackers on 2022-09-16T09:55:23-04:00

app = "voberoi-protohackers"
kill_signal = "SIGINT"
kill_timeout = 5
processes = []

[env]

[experimental]
  allowed_public_ports = []
  auto_rollback = true
  entrypoint = ["protohackers", "prime-time"]

[[services]]
  http_checks = []
  internal_port = 5001
  protocol = "tcp"
  script_checks = []
  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"

  [[services.ports]]
    port = 5001

  [[services.tcp_checks]]
    grace_period = "1s"
    interval = "15s"
    restart_limit = 0
    timeout = "2s"

